[project]
name = "wb-bad-review-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    # fully featured HTTP client for Python 3
    "httpx>=0.28.1",
    # Implements request retry for HTTPX
    "httpx-retries>=0.4.2",
    "pydantic>=2.11.9",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.1.0",
    # Pytest plugin making the output look better
    "pytest-sugar>=1.1.1",
    # Pytest plugin allowing you to run tests in multiprocessing
    "pytest-xdist>=3.8.0",
    "tortoise-orm>=0.25.1",
]
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "-n=auto",
    "--asyncio-mode=auto"
]
